version: 0.2
env:
  parameter-store:
    DOCKER_USERNAME: "/secrets/docker-hub/DOCKER_USERNAME"
    DOCKER_PASSWORD: "/secrets/docker-hub/DOCKER_PASSWORD"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yum update -y
      - yum install -y docker jq
      - nohup dockerd &
      - sleep 5
      - curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
      - echo Logging in to Docker Hub and Amazon ECR...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 061039764011.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      # Test locally first
      - cd dist/docker-compose
      - echo "Starting containers..."
      - MYSQL_PASSWORD='123456789' docker-compose up -d
      - sleep 30
      - docker-compose ps
      - docker images
      
      # Tag and push images to ECR
      - |
        echo "Tagging and pushing images to ECR..."
        declare -A images=(
          ["ui"]="public.ecr.aws/aws-containers/retail-store-sample-ui:0.8.3"
          ["assets"]="public.ecr.aws/aws-containers/retail-store-sample-assets:0.8.3"
          ["cart"]="public.ecr.aws/aws-containers/retail-store-sample-cart:0.8.3"
          ["catalog"]="public.ecr.aws/aws-containers/retail-store-sample-catalog:0.8.3"
          ["checkout"]="public.ecr.aws/aws-containers/retail-store-sample-checkout:0.8.3"
          ["orders"]="public.ecr.aws/aws-containers/retail-store-sample-orders:0.8.3"
        )
        
        for service in "${!images[@]}"; do
          echo "Processing $service..."
          docker tag "${images[$service]}" "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-$service:latest"
          docker push "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-$service:latest" || exit 1
        done
      
      # Clean up local containers
      - docker-compose down
      
      # Generate ECS task definition
      - |
        cat > task-definition.json << 'EOF'
        {
          "family": "retail-store",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "4096",
          "memory": "8192",
          "executionRoleArn": "arn:aws:iam::061039764011:role/ecsTaskExecutionRole",
          "containerDefinitions": [
            {
              "name": "ui",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-ui:latest",
              "essential": true,
              "portMappings": [{"containerPort": 8080, "hostPort": 8080}]
            },
            {
              "name": "assets",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-assets:latest",
              "portMappings": [{"containerPort": 8080}]
            },
            {
              "name": "cart",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-cart:latest",
              "portMappings": [{"containerPort": 8080}]
            },
            {
              "name": "catalog",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-catalog:latest",
              "portMappings": [{"containerPort": 8080}]
            },
            {
              "name": "checkout",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-checkout:latest",
              "portMappings": [{"containerPort": 8080}]
            },
            {
              "name": "orders",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-orders:latest",
              "portMappings": [{"containerPort": 8080}]
            }
          ]
        }
        EOF
      
      # Create ECS cluster
      - aws ecs create-cluster --cluster-name retail-store || true
      
      # Deploy to Fargate
      - aws ecs register-task-definition --cli-input-json file://task-definition.json
      - |
        TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition retail-store --query 'taskDefinition.taskDefinitionArn' --output text)
        
        # Create or update service
        aws ecs create-service \
          --cluster retail-store \
          --service-name retail-store-service \
          --task-definition $TASK_DEF_ARN \
          --desired-count 1 \
          --launch-type FARGATE \
          --network-configuration "awsvpcConfiguration={subnets=[subnet-06aa37fd],securityGroups=[sg-068ffbbf3f461bce2],assignPublicIp=ENABLED}" || \
        aws ecs update-service \
          --cluster retail-store \
          --service retail-store-service \
          --task-definition $TASK_DEF_ARN
  post_build:
    commands:
      - echo "Waiting for service to be stable..."
      - aws ecs wait services-stable --cluster retail-store --services retail-store-service || true
      - echo "Scaling down Fargate tasks..."
      - aws ecs update-service --cluster retail-store --service retail-store-service --desired-count 0 || true
artifacts:
  files:
    - dist/docker-compose/docker-compose.yml
    - task-definition.json
    - appspec.yml
  name: docker-artifact
