version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Install Docker Compose
      - curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
  build:
    commands:
      - docker-compose -f dist/docker-compose/docker-compose.yml build
      - docker-compose -f dist/docker-compose/docker-compose.yml up -d
      - sleep 30
      - docker-compose -f dist/docker-compose/docker-compose.yml ps
      - docker-compose -f dist/docker-compose/docker-compose.yml down
artifacts:
  files:
    - dist/docker-compose/docker-compose.yml
    - appspec.yml
