version: 0.2
env:
  parameter-store:
    DOCKER_USERNAME: "/secrets/docker-hub/DOCKER_USERNAME"
    DOCKER_PASSWORD: "/secrets/docker-hub/DOCKER_PASSWORD"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yum update -y
      - yum install -y docker
      - nohup dockerd &
      - sleep 5
      - curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 061039764011.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - cd dist/docker-compose
      - MYSQL_PASSWORD='123456789' docker-compose -f docker-compose.yml up -d
      - sleep 30
      - docker-compose ps
      - docker-compose down
artifacts:
  files:
    - dist/docker-compose/docker-compose.yml
    - appspec.yml
