version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18
    commands:
      - cd src/checkout
      - npm install eslint
      - cd ../cart
      - wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.3.3/checkstyle-10.3.3-all.jar
  build:
    commands:
      - java -jar checkstyle-10.3.3-all.jar -c /google_checks.xml src/main/java/
      - cd ../checkout
      - ./node_modules/.bin/eslint . --format json > eslint-report.json
  post_build:
    commands:
      - echo "Static analysis completed"
artifacts:
  files:
    - src/cart/checkstyle-result.xml
    - src/checkout/eslint-report.json
notifications:
  rules:
    - type: EVENT
      detail-type: FULL
      event-pattern:
        - PHASE_CHANGE
        - BUILD_PHASE_FAILURE
      target:
        type: SNS
        target-address: arn:aws:sns:us-east-1:061039764011:retail-store-build-notifications:3ab6d246-2dfc-4405-9544-3cc67522e948
