version: 0.2
env:
  parameter-store:
    DOCKER_USERNAME: "/secrets/docker-hub/DOCKER_USERNAME"
    DOCKER_PASSWORD: "/secrets/docker-hub/DOCKER_PASSWORD"
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - yum update -y
      - yum install -y docker jq
      - nohup dockerd &
      - sleep 5
      - curl -SL https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
      - chmod +x /usr/local/bin/docker-compose
  pre_build:
    commands:
      - echo Logging in to Docker Hub and Amazon ECR...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 061039764011.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      # Local test first
      - cd dist/docker-compose
      - MYSQL_PASSWORD='123456789' docker-compose -f docker-compose.yml up -d
      - sleep 30
      - docker-compose ps
      - docker-compose down
      
      # Tag and push images to ECR
      - |
        echo "Tagging and pushing images to ECR..."
        docker tag retail-store-sample-ui:latest 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-ui:latest
        docker tag retail-store-sample-assets:latest 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-assets:latest
        docker tag retail-store-sample-cart:latest 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-cart:latest
        docker tag retail-store-sample-catalog:latest 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-catalog:latest
        docker tag retail-store-sample-checkout:latest 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-checkout:latest
        docker tag retail-store-sample-orders:latest 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-orders:latest
        
        docker push 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-ui:latest
        docker push 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-assets:latest
        docker push 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-cart:latest
        docker push 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-catalog:latest
        docker push 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-checkout:latest
        docker push 061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-orders:latest
      
      # Generate ECS task definition
      - |
        cat > task-definition.json << 'EOF'
        {
          "family": "retail-store",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "4096",
          "memory": "8192",
          "containerDefinitions": [
            {
              "name": "ui",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-ui:latest",
              "essential": true,
              "portMappings": [{"containerPort": 8080, "hostPort": 8080}]
            },
            {
              "name": "assets",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-assets:latest",
              "portMappings": [{"containerPort": 8080}]
            },
            {
              "name": "cart",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-cart:latest",
              "portMappings": [{"containerPort": 8080}]
            },
            {
              "name": "catalog",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-catalog:latest",
              "portMappings": [{"containerPort": 8080}]
            },
            {
              "name": "checkout",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-checkout:latest",
              "portMappings": [{"containerPort": 8080}]
            },
            {
              "name": "orders",
              "image": "061039764011.dkr.ecr.us-east-1.amazonaws.com/retail-store-orders:latest",
              "portMappings": [{"containerPort": 8080}]
            },
            {
              "name": "rabbitmq",
              "image": "rabbitmq:3-management",
              "portMappings": [
                {"containerPort": 5672},
                {"containerPort": 15672}
              ]
            },
            {
              "name": "catalog-db",
              "image": "mariadb:10.9",
              "portMappings": [{"containerPort": 3306}],
              "environment": [
                {"name": "MYSQL_ROOT_PASSWORD", "value": "123456789"},
                {"name": "MYSQL_DATABASE", "value": "catalog"}
              ]
            },
            {
              "name": "orders-db",
              "image": "postgres:16.1",
              "portMappings": [{"containerPort": 5432}],
              "environment": [
                {"name": "POSTGRES_DB", "value": "orders"},
                {"name": "POSTGRES_USER", "value": "postgres"},
                {"name": "POSTGRES_PASSWORD", "value": "123456789"}
              ]
            }
          ]
        }
        EOF
      
      # Deploy to Fargate
      - aws ecs register-task-definition --cli-input-json file://task-definition.json
      - |
        # Create ECS cluster if it doesn't exist
        aws ecs describe-clusters --clusters retail-store || \
        aws ecs create-cluster --cluster-name retail-store
        
        # Get latest task definition
        TASK_DEF_ARN=$(aws ecs describe-task-definition --task-definition retail-store --query 'taskDefinition.taskDefinitionArn' --output text)
        
        # Create or update service
        aws ecs create-service \
          --cluster retail-store \
          --service-name retail-store-service \
          --task-definition $TASK_DEF_ARN \
          --desired-count 1 \
          --launch-type FARGATE \
          --network-configuration "awsvpcConfiguration={subnets=[subnet-06aa37fd],securityGroups=[sg-068ffbbf3f461bce2],assignPublicIp=ENABLED}" || \
        aws ecs update-service \
          --cluster retail-store \
          --service retail-store-service \
          --task-definition $TASK_DEF_ARN
  post_build:
    commands:
      - echo "Waiting for service to be stable..."
      - aws ecs wait services-stable --cluster retail-store --services retail-store-service
      - echo "Service is stable"
      - echo "Scaling down Fargate tasks..."
      - aws ecs update-service --cluster retail-store --service retail-store-service --desired-count 0
artifacts:
  files:
    - dist/docker-compose/docker-compose.yml
    - task-definition.json
    - appspec.yml
  name: docker-artifact
