version: 0.2
phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - docker-compose -f dist/docker-compose/docker-compose.yml build
      - docker-compose -f dist/docker-compose/docker-compose.yml up -d
      - sleep 30
      - docker-compose -f dist/docker-compose/docker-compose.yml ps
      - docker-compose -f dist/docker-compose/docker-compose.yml down
artifacts:
  files:
    - dist/docker-compose/docker-compose.yml
    - appspec.yml
